SELECT NAME, DATETIME 
  FROM (
        SELECT A.NAME NAME, A.DATETIME DATETIME 
          FROM ANIMAL_INS A 
          LEFT OUTER JOIN ANIMAL_OUTS B 
            ON A.ANIMAL_ID=B.ANIMAL_ID 
         WHERE B.DATETIME IS NULL ORDER BY 2
       ) 
 WHERE ROWNUM < 4;