SELECT ANIMAL_ID, NAME 
  FROM (SELECT A.ANIMAL_ID, A.NAME 
          FROM ANIMAL_INS A, ANIMAL_OUTS B 
         WHERE A.ANIMAL_ID = B.ANIMAL_ID 
           AND B.DATETIME-A.DATETIME > 0 
         ORDER BY B.DATETIME-A.DATETIME DESC) 
 WHERE ROWNUM < 3;